export default {
  login: "hrachgalstyan",
  id: 54104953,
  node_id: "MDQ6VXNlcjU0MTA0OTUz",
  avatar_url: "https://avatars2.githubusercontent.com/u/54104953?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/hrachgalstyan",
  html_url: "https://github.com/hrachgalstyan",
  followers_url: "https://api.github.com/users/hrachgalstyan/followers",
  following_url: "https://api.github.com/users/hrachgalstyan/following{/other_user}",
  gists_url: "https://api.github.com/users/hrachgalstyan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/hrachgalstyan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/hrachgalstyan/subscriptions",
  organizations_url: "https://api.github.com/users/hrachgalstyan/orgs",
  repos_url: "https://api.github.com/users/hrachgalstyan/repos",
  events_url: "https://api.github.com/users/hrachgalstyan/events{/privacy}",
  received_events_url: "https://api.github.com/users/hrachgalstyan/received_events",
  type: "User",
  site_admin: false,
  name: "Hrach",
  company: null,
  blog: "https://hrachgalstyan.com",
  location: "Armenia",
  email: null,
  hireable: true,
  bio: "Front-End Developer",
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2019-08-14T11:21:48Z",
  updated_at: "2020-07-08T22:05:52Z"
};
